
services:

  # 🔹 Eureka Service Registry
  service-registry:
    build: ./service-registry
    image: carscrapproject-service-registry
    ports:
    - "8761:8761"
    restart: unless-stopped


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
    restart: unless-stopped  


  # 🔹 API Gateway (ENTRY POINT)
  api-gateway:
    build: ./gateway
    image: carscrapproject-gateway
    expose:
    - "8080"
    depends_on:
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    restart: unless-stopped  

  # 🔹 MySQL Database
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: patel
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped  

  # 🔹 Auth Service
  AUTH-SERVICE:
    build: ./AUTH-SERVICE
    image: carscrapproject-auth-service
    depends_on:
      - service-registry
      - mysql
    env_file:
      - ./AUTH-SERVICE/.env
    restart: unless-stopped  

  # 🔹 Email Service
  EMAIL-SERVICE:
    build: ./Email_Service
    image: carscrapproject-email-service
    depends_on:
      - service-registry
    env_file:
      - ./Email_Service/.env
    restart: unless-stopped  

  # 🔹 Car Service
  CAR-SERVICE:
    build: ./car-service
    image: carscrapproject-car-service
    depends_on:
      - service-registry
      - mysql
    env_file:
       - ./car-service/.env
    restart: unless-stopped   

  # 🔹 Booking Service
  BOOKING-SERVICE:
    build: ./Booking-Service
    image: carscrapproject-booking-service
    depends_on:
      - service-registry
      - mysql
    env_file:
      - ./Booking-Service/.env
    restart: unless-stopped  

  # 🔹 Yard Service
  YARD-SERVICE:
    build: ./yard-service
    image: carscrapproject-yard-service
    depends_on:
      - service-registry
      - mysql
    env_file:
      - ./yard-service/.env
    restart: unless-stopped  


 


volumes:
  mysql_data: