server {
    listen 80;

    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index login.html;
        try_files $uri $uri/ /login.html;
    }

    location /api/ {
        proxy_pass http://api-gateway:8080/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}